// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCafSYf0wR7Qj-CU1PwptUTc7e9XVrDdbU',
    appId: '1:912436399609:web:eafd31db6ee9edc8d1c128',
    messagingSenderId: '912436399609',
    projectId: 'riverpod-mvvm-93799',
    authDomain: 'riverpod-mvvm-93799.firebaseapp.com',
    storageBucket: 'riverpod-mvvm-93799.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6N7dvLTGMHwmYGAjnI9xwQBw-NYpD5ac',
    appId: '1:912436399609:android:d085e5d9d5c3fcb2d1c128',
    messagingSenderId: '912436399609',
    projectId: 'riverpod-mvvm-93799',
    storageBucket: 'riverpod-mvvm-93799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTnv_1fiiw9CA8HsRl1apb_8xIcmpfG4',
    appId: '1:912436399609:ios:e3950c740847d7bad1c128',
    messagingSenderId: '912436399609',
    projectId: 'riverpod-mvvm-93799',
    storageBucket: 'riverpod-mvvm-93799.appspot.com',
    iosClientId: '912436399609-odi4rvehktnoglrn66kl1tht6arvrv6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.repositoryRiverpodMvvm',
  );
}
